services:
  soschool-app:
    container_name: soschool-app
    build: .
    restart: always
    ports:
      - "7000:7000"
    # Tambahkan baris di bawah ini agar file .env terbaca
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=https://scchl.site
    networks:
      - soschool-network

networks:
  soschool-network:
    external: true